### ISSUE TITLE
Interfaces version with INT

### ISSUE THREAD

**Issue by L-EARN** [alliedmodders/hl2sdk#17]
Hi,

I would like the interfaces version to have a INT macro as it is done in the source sdk 2013 but for csgo branch.

Like : 
# define INTERFACEVERSION_VENGINESERVER  "VEngineServer023"
# define INTERFACEVERSION_VENGINESERVER_INT 23

I could make a pull request but I have no clue how to do that as I'm using your sdk in a submodule.

Thanks.

**Comment by psychonic** [comment]
Apologies for the late response.

This was added (by Valve, not us) in the sdk2013 SDK because there are multiple games that share that engine. With the CS:GO engine, there is only a single game, and thus little need to compare what version of the engine or server interface is being used, as it will always be the latest.
