### ISSUE TITLE
Sync with upstream SDK 2013?

### ISSUE THREAD

**Issue by sigsegv-mvm** [alliedmodders/hl2sdk#30]
The upstream repo for SDK 2013 was updated 13 months ago, but those changes still haven't made their way into the sdk2013 branch. Any chance that merge could happen soon?

And if there are compat-related reasons for waiting, could we possibly get an alternative branch, e.g. `sdk2013-latest` or some such thing, for people who explicitly do want the most recent Valve code pushes? (I guess I could always fork-and-merge myself, but that's less ideal.)

---

Additional question: assuming I'm only working with TF2/MMSource/SourceMod, would there any particular problem with including/linking to the upstream version of the SDK 2013 mp directory instead of `hl2sdk-sdk2013`, or are the modifications in this repo relative to upstream important enough that doing such a thing would be a fundamentally bad idea?

Thanks.

**Comment by psychonic** [comment]
> Any chance that merge could happen soon?

Yes. I merged most or all of it locally but never got around to committing. I'll take a look at it in the next day or so and get it finished up.

For TF2, we only support using the tf2 branch. Even the latest Source SDK 2013 version is over a year old and there have been breaking interface changes since then. That would generally be an issue with trying to use the sdk2013 branch of this or the official SDK for TF2.

**Comment by sigsegv-mvm** [comment]
Huh. I've had a fairly massive, sprawling TF2 extension for a while now where I've been using the `hl2sdk-2013` tree, and as far as I know I've gotten away without having any major issues.

Maybe it helps that I don't make super extensive use of global interfaces and tend to lean more toward absurd quantities of detours and verified patches, where I can check against the actual disassembled binaries... oh, and thunks to native functions, lots of thunks. Actually it amazes me that it's as non-crashy as it is.

**Comment by TheCreeper** [comment]
Any progress on getting the latest Source SDK 2013 version merged?
